### ISSUE TITLE
Several errors

### ISSUE THREAD

**Issue by Max33M** [NotARobot6969/KextUpdater#1]
Kext Lilu was detected, but was unable to update. Please report which kext this is as a GitHub issue!
System.IO.IOException: Cross-device link
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at Program.<Main>$(String[] args) in /Users/alexmyers/KextUpdater3/KextUpdater/Program.cs:line 123
VoodooI2CAtmelMXT was not found in the database. Please create a pull request to add it or an issue with details!
Kext itlwm was detected, but was unable to update. Please report which kext this is as a GitHub issue!
System.IO.IOException: Cross-device link
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at Program.<Main>$(String[] args) in /Users/alexmyers/KextUpdater3/KextUpdater/Program.cs:line 123
Kext AppleALC was detected, but was unable to update. Please report which kext this is as a GitHub issue!
System.IO.IOException: Cross-device link
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at Program.<Main>$(String[] args) in /Users/alexmyers/KextUpdater3/KextUpdater/Program.cs:line 123
Kext IntelBluetoothFirmware was detected, but was unable to update. Please report which kext this is as a GitHub issue!
System.IO.IOException: Cross-device link
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at Program.<Main>$(String[] args) in /Users/alexmyers/KextUpdater3/KextUpdater/Program.cs:line 123
VoodooI2CSynaptics was not found in the database. Please create a pull request to add it or an issue with details!
BlueToolFixup was not found in the database. Please create a pull request to add it or an issue with details!
Kext WhateverGreen was detected, but was unable to update. Please report which kext this is as a GitHub issue!
System.IO.IOException: Cross-device link
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at Program.<Main>$(String[] args) in /Users/alexmyers/KextUpdater3/KextUpdater/Program.cs:line 123
AirportItlwm was not found in the database. Please create a pull request to add it or an issue with details!
BrightnessKeys was not found in the database. Please create a pull request to add it or an issue with details!
VoodooI2CHID was not found in the database. Please create a pull request to add it or an issue with details!
VoodooI2CFTE was not found in the database. Please create a pull request to add it or an issue with details!
VoodooI2CELAN was not found in the database. Please create a pull request to add it or an issue with details!
BigSurface was not found in the database. Please create a pull request to add it or an issue with details!
VirtualSMC was not found in the database. Please create a pull request to add it or an issue with details!
USBPorts was not found in the database. Please create a pull request to add it or an issue with details!
![Screen Shot 2022-07-16 at 11 04 09 PM](https://user-images.githubusercontent.com/109448989/179383487-54dba09d-dd8e-48f6-80aa-d9538b12a4f3.png)

**Comment by not-nullptr** [comment]
Hey, thanks for reporting this as an issue! I'm working on it as we speak. Were you working on an external device (e.g a USB stick)?

**Comment by not-nullptr** [comment]
Should be fixed with latest commit, will compile a release now.

**Comment by Max33M** [comment]
Awesome! I will check it out tonight, sadly I’m working now

**Comment by Max33M** [comment]
This was my main system actually. Surface pro 7, open core with Monterey
(latest update.)
The EFI is copied over to the system, so no usb is needed to boot opencore.
Hope this helps, love the idea! We really need a solid kext updater.

Warm regards,
Alex
